"""Cache: autogen schema change

Revision ID: f88b563f9659
Revises: c6ef49f29d64
Create Date: 2025-05-13 13:17:59.269972

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f88b563f9659"
down_revision: Union[str, None] = "c6ef49f29d64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sec_filing_hierarchy", sa.Column("status", sa.UnicodeText(), nullable=True)
    )
    op.execute(
        "UPDATE sec_filing_hierarchy SET status = 'complete' WHERE status IS NULL"
    )
    op.alter_column(
        "sec_filing_hierarchy",
        "status",
        existing_type=sa.UnicodeText(),
        nullable=False,
        server_default="in-progress",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sec_filing_hierarchy", "status")
    # ### end Alembic commands ###
